LineTrackerInterns:
  address: "trackers_brubotics/LineTrackerInterns"

MpcTrackerInterns:
  address: "trackers_brubotics/MpcTrackerInterns"

BypassTracker:
  address: "trackers_brubotics/BypassTracker"

AlphaDrg:
  address: "trackers_brubotics/AlphaDrg"

